services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    command: ['npm', 'run', 'dev:api']
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: development
    volumes:
      - ..:/workspace
    working_dir: /workspace

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    command: ['npm', 'run', 'dev:web']
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - ..:/workspace
    working_dir: /workspace
    depends_on:
      - api
